# Generated by Django 4.2.9 on 2024-01-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("BadgeID", models.AutoField(primary_key=True, serialize=False)),
                ("BadgeName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("IconURL", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("CourseID", models.AutoField(primary_key=True, serialize=False)),
                ("CourseName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("PublicCourse", models.BooleanField()),
                ("CourseMaterialsURL", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("DepartmentID", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("EmployeeID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=20)),
                ("HireDate", models.DateField()),
                ("EmployeePhotoURL", models.URLField()),
                (
                    "Department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                ("JobTitleID", models.AutoField(primary_key=True, serialize=False)),
                ("JobTitleName", models.CharField(max_length=255)),
                ("Responsibilities", models.TextField()),
                ("Qualifications", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Salesman",
            fields=[
                ("SalesmanID", models.AutoField(primary_key=True, serialize=False)),
                ("SalesTarget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "SalesAchievement",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("SalesProgress", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("StatusID", models.AutoField(primary_key=True, serialize=False)),
                ("StatusName", models.CharField(max_length=255)),
                ("StatusDescription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("TaskID", models.AutoField(primary_key=True, serialize=False)),
                ("TaskName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Deadline", models.DateField()),
                ("TaskDuration", models.IntegerField()),
                ("TaskPriority", models.CharField(max_length=10)),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                ("TrainerID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Phone", models.CharField(max_length=20)),
                ("Qualifications", models.TextField()),
                ("Certificates", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainerCourseAssignment",
            fields=[
                ("AssignmentID", models.AutoField(primary_key=True, serialize=False)),
                ("AssignmentDate", models.DateField()),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
                (
                    "Trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.trainer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskQualityRating",
            fields=[
                ("RatingID", models.AutoField(primary_key=True, serialize=False)),
                ("QualityRating", models.IntegerField()),
                (
                    "Reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.employee",
                    ),
                ),
                (
                    "Task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                ("ProgressID", models.AutoField(primary_key=True, serialize=False)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("Comments", models.TextField()),
                (
                    "Status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.status",
                    ),
                ),
                (
                    "Task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskDeliverable",
            fields=[
                ("DeliverableID", models.AutoField(primary_key=True, serialize=False)),
                ("DeliverableName", models.CharField(max_length=255)),
                ("DeliverableDescription", models.TextField()),
                ("DeliverableURL", models.URLField()),
                (
                    "Task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesmanCourseAssignment",
            fields=[
                ("AssignmentID", models.AutoField(primary_key=True, serialize=False)),
                ("AssignmentDate", models.DateField()),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
                (
                    "Salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.salesman"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                ("PerformanceID", models.AutoField(primary_key=True, serialize=False)),
                ("TaskPoints", models.IntegerField()),
                ("QualityPoints", models.IntegerField()),
                ("HoursWorkedPoints", models.IntegerField()),
                ("MeetingAttendancePoints", models.IntegerField()),
                ("TotalPoints", models.IntegerField()),
                (
                    "Badge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.badge",
                    ),
                ),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("MeetingID", models.AutoField(primary_key=True, serialize=False)),
                ("MeetingDate", models.DateField()),
                ("AttendanceStatus", models.BooleanField()),
                ("MinutesDuration", models.IntegerField()),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                ("SkillID", models.AutoField(primary_key=True, serialize=False)),
                ("SkillName", models.CharField(max_length=255)),
                ("SkillLevel", models.IntegerField()),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeBadge",
            fields=[
                (
                    "EmployeeBadgeID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("DateEarned", models.DateField()),
                (
                    "Badge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.badge",
                    ),
                ),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="JobTitle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.jobtitle",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="DepartmentHead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.employee",
            ),
        ),
    ]
