# Generated by Django 4.1.4 on 2024-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="badge", name="IconURL",),
        migrations.AddField(
            model_name="badge",
            name="BadgeImage",
            field=models.ImageField(blank=True, null=True, upload_to="badge_images/"),
        ),
    ]
