# Generated by Django 4.1.4 on 2024-01-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_badge_iconurl_badge_badgeimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="EmployeePhotoURL",),
        migrations.AddField(
            model_name="employee",
            name="EmployeePhoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="Employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pages.employee"
            ),
        ),
    ]
