# Generated by Django 4.1.4 on 2024-01-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_employee_employeephotourl_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="department", name="DepartmentHead",),
    ]
