# Generated by Django 4.1.4 on 2024-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="EmployeePhotoURL",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
