# Generated by Django 4.1.4 on 2024-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_performance_employee"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskdeliverable", name="DeliverableURL",),
        migrations.AddField(
            model_name="taskdeliverable",
            name="DeliverableFile",
            field=models.FileField(
                default="default_file.pdf", upload_to="deliverables/"
            ),
        ),
    ]
