# Generated by Django 4.1.4 on 2024-01-22 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_remove_taskdeliverable_deliverableurl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
