# Generated by Django 4.2.10 on 2024-02-11 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_performance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='InstructorName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeePhoto',
            field=models.ImageField(blank=True, default='employee_photos/default-employee.webp', null=True, upload_to='employee_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 20, 20, 19, 675939)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(default='default description', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskDuration',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskPriority',
            field=models.CharField(default='normal', max_length=10, null=True),
        ),
    ]
