# Generated by Django 4.2.10 on 2024-02-12 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_course_duration_course_instructorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='PerHour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 15, 6, 10, 776314)),
        ),
    ]
