# Generated by Django 4.2.10 on 2024-02-13 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_employee_location_employee_perhour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 10, 46, 18, 36638)),
        ),
    ]
