# Generated by Django 4.2.10 on 2024-02-15 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_employee_hiredate_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 16, 36, 58, 412254)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 16, 36, 58, 413304), null=True),
        ),
    ]
