# Generated by Django 4.2.10 on 2024-02-16 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_employee_hiredate_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 21, 32, 43, 723323)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 21, 32, 43, 724393), null=True),
        ),
    ]
