# Generated by Django 4.2.10 on 2024-02-27 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_employee_hiredate_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 17, 46, 3, 645051)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 17, 46, 3, 646114), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.status'),
        ),
    ]
