# Generated by Django 4.2.10 on 2024-02-28 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_employee_hiredate_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployeeTarget',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 13, 57, 24, 524013)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 13, 57, 24, 525200), null=True),
        ),
    ]
