# Generated by Django 4.2.10 on 2024-03-15 15:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_activity_donedate_alter_employee_hiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='DoneDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 15, 2, 37, 844364)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 15, 2, 37, 845763), null=True),
        ),
    ]
