# Generated by Django 4.2.10 on 2024-03-19 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_trainer_location_alter_employee_hiredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Price',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 13, 7, 49, 253653)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 13, 7, 49, 255056), null=True),
        ),
    ]
