# Generated by Django 4.2.10 on 2024-03-21 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_rename_price_trainer_priceperhour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 10, 11, 8, 94237)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 10, 11, 8, 95475), null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Location',
            field=models.TextField(default='EGY', max_length=20),
        ),
    ]
