# Generated by Django 4.2.10 on 2024-03-21 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_trainer_comments_alter_employee_hiredate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='PricePerHour',
            new_name='rates',
        ),
        migrations.AlterField(
            model_name='employee',
            name='HireDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 10, 22, 4, 277797)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 10, 22, 4, 279034), null=True),
        ),
    ]
